### ISSUE TITLE
uploads doesn't appear in mobile app

### ISSUE THREAD

**Issue by simonfromwales** [alextran1502/immich-cli#5]
I uploaded a few old photographs using this cli application.

The photos appears to upload successively, but do not appear in the mobile app at all.

**Comment by alextran1502** [comment]
Hi @simonfromwales, the CLI tool is currently out-of-date with the server. I will keep you posted when it is updated.

**Comment by alextran1502** [comment]
CLI tool is now updated with version 0.4.0
